### ISSUE TITLE
package.json error

### ISSUE THREAD

**Issue by TrezorTop** [apollo-server-integrations/apollo-server-integration-koa#126]
`node_modules/@as-integrations/koa/dist/index.d.ts:2:75 - error TS1479:` The current file is a CommonJS module whose imports will produce 'require' calls; however, the referenced file is an ECMAScript module and cannot be imported w
ith 'require'. Consider writing a dynamic 'import("@apollo/server")' call instead.

**Comment by TrezorTop** [comment]
I opened pull request: [PR](https://github.com/apollo-server-integrations/apollo-server-integration-koa/pull/127)

**Comment by trevor-scheer** [comment]
This integration only distributes CommonJS, not ESM. If you're seeing an error related to this, you probably need to adjust your TypeScript configuration. Your PR for just changing to `"type": "module"` is at least a breaking change for existing users (and I haven't validated if other changes are also necessary). It's possible to support both, which is what `@apollo/server` does, but it requires a bit more work. I'd welcome a PR that introduces support for both!

If you can share a repo / reproduction I can try to help you diagnose the configuration issue.

**Comment by TrezorTop** [comment]
Oh, I see, sorry for my noobyness. Going to research deeper
