### ISSUE TITLE
Graphql middleware not working (while a routing middleware exists)

### ISSUE THREAD

**Issue by Mathusan** [apollo-server-integrations/apollo-server-integration-koa#171]
`const app: Koa<DefaultState, DefaultContext> = new Koa();

//graphql
const httpServer = http.createServer(app.callback());

/* Database connection: **/
connection();

const apolloServer = new ApolloServer({
  typeDefs,
  resolvers,
  plugins: [ApolloServerPluginDrainHttpServer({ httpServer })],
});

/* middleware: **/
app.use(cors(corsOptions));
app.use(json());
app.use(bodyParser());
**app.use(userRouter.routes()).use(userRouter.allowedMethods);**

const apolloStart = async () => {
  await apolloServer.start();
  app.use(
    koaMiddleware(apolloServer, {
      context: async ({ ctx }) => ({ token: ctx.headers.token }),
    })
  );
};

apolloStart();

/* routes: **/

/* error handling middleware: **/
app.on('error', errorMiddleware);

/* server listen: **/
const server = async () => {
  await new Promise<void>((resolve) =>
    httpServer.listen({ port: Number(config.port) }, resolve)
  );
  console.log(`Server running at ${Number(config.port)}`);
};

server();

export { app, server };`

When the routing exists the graphql middleware fails to run resulting in the graphql endpoint not found.
Any idea to why this is happening

**Comment by Mathusan** [comment]
`app.use(cors(corsOptions));
app.use(json());
app.use(bodyParser());
app.use(graphqlRouter.routes());
app.use(userRouter.routes()).use(userRouter.allowedMethods);

const apolloStart = async () => {
  await apolloServer.start();
  graphqlRouter.post(
    '/graphql',
    koaMiddleware(apolloServer, {
      context: async ({ ctx }) => ({ token: ctx.headers.token }),
    })
  );
};

apolloStart();`


Fix above,
Used the graphql middleware with a koa router instead of directly applying gql middleware to koa App instance, still wondering why this was an issue

**Comment by trevor-scheer** [comment]
It looks like you changed the ordering of your graphql route and your user routes. Do your user routes call `next()`? If not then that's the end of your middleware chain and the koaMiddleware would never be invoked.

https://koajs.com/#cascading

I don't think this is an issue with this integration so I'm going to close it, but happy to reopen if there's actually an issue.
