### ISSUE TITLE
How do I specify a URL path where the default behavior is that all URL path are OK

### ISSUE THREAD

**Issue by quirkybird** [apollo-server-integrations/apollo-server-integration-koa#195]
I see apollo-server-express, the default URL is `/graphql`, which can also be customized,look like:  
```js
.../
app.use(
  '/graphql',
  cors<cors.CorsRequest>(),
  express.json(),
  expressMiddleware(server, {
    context: async ({ req }) => ({ token: req.headers.token }),
  }),
.../
);
```
I tried the same thing. It didn't work

**Comment by vcellu** [comment]
Hi, did you resolve this issue?

**Comment by matthew-gordon** [comment]
Hi @quirkybird, you can see a previously closed issue on this topic here https://github.com/apollo-server-integrations/apollo-server-integration-koa/issues/61.

You can try using the [@koa/router](https://github.com/koajs/router) package:

```typescript
import koa from 'koa';
import Router from '@koa/router';

const app = new Koa();
const router = new Router();

router.get('/graphql', koaMiddleware(server));

app
  .use(router.routes())
  .use(router.allowedMethods());
```

Hope this helps!

**Comment by quirkybird** [comment]
@matthew-gordon thank you！！！！！！！！！

**Comment by quirkybird** [comment]
I still can't solve this problem, can you give me the full code, like the README, because here it is
```js
  app.use(
    koaMiddleware(server, {
      context: async ({ ctx }) => ({ token: ctx.headers.token }),
    })
  );
```

**Comment by matthew-gordon** [comment]
> I still can't solve this problem, can you give me the full code, like the README, because here it is
> 
> ```js
>   app.use(
>     koaMiddleware(server, {
>       context: async ({ ctx }) => ({ token: ctx.headers.token }),
>     })
>   );
> ```

Ho @quirkybird, it looks like you still aren't using the `@koa/router` package, following is a small snippet. If you still can't get this working I would be happy to take a look at a repo and code that you have to help troubleshoot.

The code snippet you provided is available at the root route `/` however here is a typescript example

Note: This example is using typescript

```typescript
import http from "http";
import Koa from "koa";
import bodyParser from "koa-bodyparser";
import cors from "@koa/cors";
import { ApolloServer } from "@apollo/server";
import { ApolloServerPluginDrainHttpServer } from "@apollo/server/plugin/drainHttpServer";
import { koaMiddleware } from "@as-integrations/koa";
import Router from "@koa/router";

// The GraphQL schema
const typeDefs = `#graphql
  type Query {
    hello: String
  }
`;

// A map of functions which return data for the schema.
const resolvers = {
  Query: {
    hello: () => "world",
  },
};

export default async function start() {
  const router = new Router();
  const app = new Koa();
  const httpServer = http.createServer(app.callback());

  // Set up Apollo Server
  const server = new ApolloServer({
    typeDefs,
    resolvers,
    plugins: [ApolloServerPluginDrainHttpServer({ httpServer })],
  });
  await server.start();

  app.use(cors());
  app.use(bodyParser());
  router.all(
    "/graphql",
    koaMiddleware(server, {
      context: async ({ ctx }) => ({ token: ctx.headers.token }),
    })
  );

  app.use(router.routes()).use(router.allowedMethods());

  await new Promise<void>((resolve) =>
    httpServer.listen({ port: 4000 }, resolve)
  );
  console.log(`🚀 Server ready at http://localhost:4000/graphql`);
}

start()
```

**Comment by quirkybird** [comment]
So now we have to use the following code at the end?
```js
app.use(router.routes()) ;
app.use(router.allowedMethods());
```

**Comment by quirkybird** [comment]
@matthew-gordon ,I see what you mean, but I configured the router and then I started the server here, which seems to be in a different order, so what does koaMiddleWare() do?

**Comment by quirkybird** [comment]
@matthew-gordon Thank you very much for your patience
