### ISSUE TITLE
Request: build dist before publishing instead of on postinstall

### ISSUE THREAD

**Issue by MarcPorciuncula** [apollo-server-integrations/apollo-server-integration-koa#40]
Hi there, thanks for creating this integration!

Unfortunately I am unable to run this package in production, as the `postinstall` script tries to run `tsc`. 

In my production deployments `devDependencies` are not installed. So when npm performs `postinstall` on `@as-integrations/koa`, the call to `tsc` fails as there are a bunch of `@types` packages missing.

It appears this package builds the dist itself on postinstall instead of building and including the dist in the published package. Is there a particular reason for this? 

You can avoid having to run the typescript compiler on consumers machines by changing the "postinstall" script to "prepare" or "prepack", then add `"files": ["dist"]` so the built files would be included in the package.

**Comment by trevor-scheer** [comment]
Thanks for the report @MarcPorciuncula! Should be resolved in v0.2.1 👍

**Comment by MarcPorciuncula** [comment]
Thanks for the speedy resolution @trevor-scheer!
