### ISSUE TITLE
recommend actively-maintained "koa-body" rather than un-maintained "koa-bodyparser"

### ISSUE THREAD

**Issue by iambumblehead** [apollo-server-integrations/apollo-server-integration-koa#60]
Recommend actively-maintained [koa-body][0] over un-maintained and less-complete [koa-bodyparser.][1]
```console
`ctx.request.body` is not set; this probably means you forgot to set
up the `koa-bodyparser` middleware before the Apollo Server middleware.
```

[0]: https://www.npmjs.com/package/koa-body
[1]: https://www.npmjs.com/package/koa-bodyparser

**Comment by matthew-gordon** [comment]
@iambumblehead I am hesitant to change out a dependency that hasn't been deprecated and is part of the main `koajs` repo, switching to the new dependency breaks the integration test suite so it wouldn't work well for our use case. I imagine this could be remedied with some slight configuration to `koa-body` to get it passing with use, though we only have `koa-bodyparser` as a dev dependency (also recommended in the docs). It is certainly a good idea to use packages that are actively maintained, so if you feel strongly I definitely encourage a PR with the changes.
