### ISSUE TITLE
How to mount at /graphql?

### ISSUE THREAD

**Issue by justinpincar** [apollo-server-integrations/apollo-server-integration-koa#76]
Hi, it seems like this mounts it at the root, which conflicts with our other routes. 

How can this be customized to restore the previous v3 behavior of mounting at `/graphql`?

**Comment by matthew-gordon** [comment]
You can use koa-router or similar library to mount this middleware at a specified path.

**Comment by justinpincar** [comment]
Thanks, I just updated my comment as you posted this.

I tried using koa-router initially mounting as middleware, which did not work:

```
const graphqlRouter = new Router();
const graphqlMiddleware = koaMiddleware(apolloServer, { context });
graphqlRouter.use('/graphql', graphqlMiddleware);
app.use(graphqlRouter.routes());
app.use(graphqlRouter.allowedMethods());
```

But the `.all()` method does seem to work, so I'm all set.  Thanks for your response.

**Comment by iambumblehead** [comment]
anther earlier suggested solution using koa-body is here https://github.com/apollo-server-integrations/apollo-server-integration-koa/issues/61
