### ISSUE TITLE
Getting 404 response for the code in README.md

### ISSUE THREAD

**Issue by akshathaPrasad** [apollo-server-integrations/apollo-server-integration-koa#90]
The server ready message is printed onto the console but on accessing the [URL](http://localhost:4000/) getting 'Not Found'. Please help.

**Comment by duinness** [comment]
Hi Akshatha,
I'm trying to learn how Apollo Server 4 works with the koa services I'm using.
I've copy/pasted the code from the example in to a .mjs file, ran yarn init, ran yarn install, and started it with node 18 on a mac and it is working as expected for me.
Could you provide more details?

**Comment by akshathaPrasad** [comment]
I followed the same steps and its working in my personal machine but failing in the office machine. Not sure why? Anyway, thank you for the follow up. I'm closing the issue.
